#' @title
#' Harmonics
#'
#' @description
#' A set of harmonic data for NOAA CO-OPS tide stations. Includes lunar node year constituent corrections.
#'
#' @details
#' All tide station data, including harmonic constituents and subordinate station offsets, were
#' downloaded from the \href{https://api.tidesandcurrents.noaa.gov/api/prod/}{NOAA CO-OPS Data API}
#'
#' Lunar node year data captures the effects of the 18.6 year lunar orbital cycle on amplitudes
#' and phase of tidal constituents. Values for years 1700 to 2100 were extracted from the
#' \href{https://flaterco.com/files/xtide/congen_output.txt}{congen_output.txt}
#' dataset generated by David Flater for \href{https://flaterco.com/xtide/}{XTide}.
#'
#' The names of some constituents needed to be updated to match naming conventions used by NOAA CO-OPS. The
#' \href{https://cran.r-project.org/web/packages/TideHarmonics/TideHarmonics.pdf}{TideHarmonics::harmonics}
#' dataset was used to aid in making translations between naming conventions. Documentation associated
#' with the \code{congen} program at \href{https://flaterco.com/files/xtide/congen_input.txt}{XTide}
#' also served as an invaluable resource to update constituent names.
"harmonics"
